Initialize Gradle Multi-Project Structure
f-lab-edu/challenge-hub pull request #1
Opened 2023-11-05 12:42 UTC by eogml0716

# Gradle 멀티 프로젝트 구조 초기화

## 개요
본 PR은 `challenge-hub` 애플리케이션을 위한 Gradle 멀티 프로젝트 빌드 구성의 초석을 마련합니다. 
이는 각 앱 모듈을 별도로 독립적으로 관리할 수 있는 기본 프로젝트 구조를 생성하는 것을 목표로 합니다.

## 변경 사항
- 멀티 프로젝트 레이아웃을 정의하기 위한 `settings.gradle`을 추가하였습니다.
- `user-authentication`, `challenge-management`, `community-interaction` 서브 프로젝트 디렉토리를 생성하였습니다.
- 각 서브 프로젝트에 필요한 Spring Boot 의존성을 포함한 기본 `build.gradle`을 설정하였습니다.

2023-11-06 06:58 UTC, f-lab-lyan commented
PR 확인했습니다. 간단하게 코멘트를 드리면, 일단 필요없는 부분들을 삭제해보면 좋을 것 같습니다. 예를 들면 .gitignore같은 부분에 과도하게 많은 내용이 들어있는데, 지금 대희님에게 꼭 필요한 내용을 제외하고 다 지우면 좋을 것 같습니다. 그리고 build.gradle의 경우, 지금 설정을 그대로 쓰면, 루트 디렉토리에도 java설정이 들어가게 되는데요. 실제로 root에는 자바 코드가 없으니까, 거기에 자바 설정을 넣을 필요는 없을 것 같습니다. 어떻게 수정하면 좋을지 고민해 보시면 좋을 것 같습니다.

2023-11-06 08:37 UTC, f-lab-lyan commented on .gitignore
> +out/
이 설정들이 실제로 다 사용되는것인가요? 하나씩 확인해보시면 좋을 것 같아요.

2023-11-06 08:40 UTC, eogml0716 commented on .gitignore
> +out/
점점 감이 잡혀가네요. 감사드립니다. 신경 더 써가면서 해보겠습니다.

2023-11-06 08:50 UTC, f-lab-lyan commented on .gitignore
> +out/
넵, 정말로 딱 필요한 코드만 남기는 것이 목표입니다. :-)

2023-11-09 07:32 UTC, jongyoul requested changes
각 서브 모듈에 스프링 부트 웹 실행을 위한 디펜던시와 어플리케이션 클래스를 하나씩 만들어서 실제로동작하는지 확인해 보면 좋을 것 같습니다. 그리고 root 에 클래스들이 있는데, 이 파일들은 위치가 맞을까요?

2023-11-09 07:32 UTC, jongyoul commented
그리고 빈 파일이 두 개가 있는데요. 이 파일들은 필요없으면 지워도 될 것 같습니다.

2023-11-09 08:14 UTC, f-lab-lyan commented
그리고 빈 파일이 두 개가 있는데요. 이 파일들은 필요없으면 지워도 될 것 같습니다.

2023-11-09 12:03 UTC, f-lab-lyan commented on challenge-management/build.gradle
> +    id 'io.spring.dependency-management' version '1.1.3'
https://docs.spring.io/spring-boot/docs/current/reference/html/dependency-versions.html

2023-11-13 06:56 UTC, f-lab-lyan commented on settings.gradle
> +
```suggestion
```

2023-11-13 06:56 UTC, f-lab-lyan commented on user-authentication/build.gradle
> +    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.10.0'
```suggestion
    testImplementation 'org.junit.jupiter:junit-jupiter-api'
```

2023-11-13 06:56 UTC, f-lab-lyan commented on community-interaction/build.gradle
> +    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.10.0'
```suggestion
    testImplementation 'org.junit.jupiter:junit-jupiter-api'
```

2023-11-13 06:57 UTC, f-lab-lyan commented on challenge-management/build.gradle
> +    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.10.0'
```suggestion
    testImplementation 'org.junit.jupiter:junit-jupiter-api'
```

2023-11-13 06:58 UTC, f-lab-lyan commented on challenge-management/build.gradle
> +    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.10.0'
```suggestion
    testImplementation 'org.junit.jupiter:junit-jupiter-api'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'

```

2023-11-16 03:05 UTC, f-lab-lyan approved these changes

2023-11-16 06:39 UTC, merged