Controller 구현- Implement API Endpoints for User, Challenge, Community Features
f-lab-edu/challenge-hub pull request #3
Opened 2023-11-13 06:55 UTC by eogml0716

## 개요
이 Pull Request는 사용자 인증 및 프로필 관리, 챌린지 관리 및 참여, 그리고 사회적 상호작용 기능에 대한 기본 및 확장 API 엔드포인트를 구현합니다. 또한, 기타 추가 기능 및 서비스도 포함되어 있습니다.

## 상세 내용
PR에는 다음과 같은 주요 구성요소가 포함되어 있습니다:

### 사용자 인증 및 프로필 관리 API
- 사용자 등록, 이메일 인증, 소셜 계정 가입, 이메일 로그인, 소셜 로그인, 2단계 인증, 비밀번호 재설정, 프로필 조회 및 업데이트 엔드포인트 구현.
- 프로필 사진 업로드 및 성취 목록 조회 기능 확장.

### 챌린지 관리 및 참여 API
- 챌린지 생성, 목록 조회, 상세 조회, 수정, 삭제, 참여, 진행 상태 추적 및 성과 등록에 대한 기본 API 구현.
- 챌린지 태그, 이미지, 초대, 댓글, 규칙, 설정, 진행 상황 보고, 리더보드, 참여자 관리, 피드백, 분석 기능 확장.

### 사회적 상호작용 및 커뮤니케이션 API
- 친구 추가, 친구 목록 및 팔로워 목록 조회, 그룹 생성, 그룹 메시지 전송 및 조회에 대한 기본 API 구현.
- 다른 사용자 프로필 조회, 개인 메시지 전송, 그룹 멤버 관리, 친구 요청 처리, 커뮤니티 피드 조회, 그룹 이벤트 관리, 커뮤니티 포스트 관리 기능 확장.

### 기타 추가 기능 및 서비스
- 알림 설정, 사용자 활동 분석, 챌린지별 분석, 자주 묻는 질문(FAQ) 조회 API 구현.

## 통합 테스트
- 컨트롤러 엔드포인트가 더미 데이터로 제대로 동작하는지 확인하기 위한 통합 테스트 추가.

## 참고
- 현재 구현된 모든 엔드포인트는 더미 데이터를 반환합니다. 실제 비즈니스 로직 통합은 향후 개발 과정에서 진행될 예정입니다.

(구현 내용은 변경 될 수 있습니다.)

2023-11-13 07:05 UTC, f-lab-lyan commented on community-interaction/src/main/java/daehee/challengehub/controller/CommunityInteractionController.java
> +public class CommunityInteractionController {
이 컨트롤러에 너무 많은 API가 있는 것 같아요. friends, follows, groups, user, community등 너무 많은 게 한꺼번에 들어가 있는 것 같아요. 특별히 다 넣어야하는 이유가 있는게 아니라면, 각각 다른 Controller로 분리하고, @RequestMapping으로 prefix를 줘보는건 어떨까요?

2023-11-13 13:40 UTC, eogml0716 commented on community-interaction/src/main/java/daehee/challengehub/controller/CommunityInteractionController.java
> +public class CommunityInteractionController {
@f-lab-lyan 저도 너무 많다고 생각이 들어서 일부 기능들은 제거하려고 생각 중 입니다. API 제거 하고도 너무 많아보이면 컨트롤러 나눠보도록 하겠습니다!

2023-11-15 03:00 UTC, f-lab-lyan requested changes
대희님, 이 PR하나에 모든 내용을 다 담으실 필요는 없습니다. 그렇게 되면, 오히려 리뷰하는데 시간이 더 걸리기도 하고, 애초에 PR을 만드는 이유도 모호해지기 때문입니다. PR은 최소한의 단위로 작성하시고, 여러가지 기능을 추가 하고 싶으시면, 여러 브랜치에서 각각 작업하시는 게 더 좋을 것 같습니다. (파일 40개에 1773라인 수정이라서.... :-))

2023-11-15 11:56 UTC, f-lab-lyan commented
간단히 코드를 리뷰해보면, API서버니까, 기본적으로 Json을 output으로 하는 것이 좋을 것 같습니다. 그리고 테스트 코드에서 jsonPath를 이용해서 검증하시는데, 물론 간단하게 그렇게 하실 수도 있지만, 이왕이면, ObjectMapper를 이용해서 결과값이 내가 원하는 구조인지 확인하시는 게 더 좋아보입니다.

2023-11-25 08:08 UTC, closed without merging